const chatsEvents = {
    'CHATS_FETCH_START': 'CHATS_FETCH_START',
    'CHATS_FETCH_SUCCESS': 'CHATS_FETCH_SUCCESS',
    'CHATS_FETCH_ERROR': 'CHATS_FETCH_ERROR',
    'CREATE_CHAT_START': 'CREATE_CHAT_START',
    'CREATE_CHAT_SUCCESS': 'CREATE_CHAT_SUCCESS',
    'CREATE_CHAT_ERROR': 'CREATE_CHAT_ERROR',
    'PARTICIPANT_ONLINE': 'PARTICIPANT_ONLINE',
    'PARTICIPANT_OFFLINE': 'PARTICIPANT_OFFLINE',
    'NEW_MESSAGE': 'NEW_MESSAGE',
    'SEND_MESSAGE': 'SEND_MESSAGE',
    'SEND_MESSAGE_ERROR': 'SEND_MESSAGE_ERROR',
    'NEW_PARTICIPANT': 'NEW_PARTICIPANT',
    'ADD_PARTICIPANT_ERROR': 'ADD_PARTICIPANT_ERROR'
};

module.exports = chatsEvents;